"""
Django settings for rzd project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = os.path.join(BASE_DIR, 'logs')



# Application definition

INSTALLED_APPS = [
    'material',
    'material.admin',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'corsheaders',
    'rest_framework',
    'sorl.thumbnail',
    'colorfield',
    'core',
    'apps.material_admin',
    'apps.project',
    'apps.client',
    'apps.diploma',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [

            BASE_DIR / 'apps/material_admin/templates',
            BASE_DIR / 'core/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),


    'COERCE_DECIMAL_TO_STRING': False,

    'COERCE_NULL_STRINGS': True,



    # 'DATE_FORMAT': "%d.%m.%Y",
}


LANGUAGE_CODE = 'ru-rus'

TIME_ZONE = 'Asia/Yakutsk'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

MATERIAL_ADMIN_SITE = {
    'HEADER': ('ЗабЦифра'),  # Admin site header
    'TITLE': ('ЗабЦифра'),  # Admin site title
    'FAVICON': 'logo_big.svg',  # Admin site favicon (path to static should be specified)
    'MAIN_BG_COLOR': '',  # Admin site main color, css color should be specified
    'MAIN_HOVER_COLOR': '',  # Admin site main hover color, css color should be specified
    'PROFILE_PICTURE': 'admin/fon.jpg',
    # Admin site profile picture (path to static should be specified)
    'PROFILE_BG': 'admin/fon.jpg',  # Admin site profile background (path to static should be specified)
    'LOGIN_LOGO': 'admin/fon.jpg',  # Admin site logo on login page (path to static should be specified)
    'LOGOUT_BG': 'admin/fon.jpg',
    # Admin site background on login/logout pages (path to static should be specified)
    'SHOW_THEMES': False,  # Show default admin themes button
    'TRAY_REVERSE': False,  # Hide object-tools and additional-submit-line by default
    'NAVBAR_REVERSE': True,  # Hide side navbar by default
    'SHOW_COUNTS': True,  # Show instances counts for each model
    'APP_ICONS': {
        # Set icons for applications(lowercase), including 3rd party apps, {'application_name': 'material_icon_name', ...}
        'core': 'apps',
    },
    'MODEL_ICONS': {
        # Set icons for models(lowercase), including 3rd party models, {'model_name': 'material_icon_name', ...}
    }
}
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_AGE = 259200000
SESSION_COOKIE_HTTPONLY = False

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
]



MEDIA_ROOT = os.path.join(BASE_DIR, 'public_html', 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'public_html', 'static')


APPEND_SLASH = True


from core.local_settings import *







