# Generated by Django 4.2.19 on 2026-02-09 09:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя проекта')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Url')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('show_in_main', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
                ('order_index', models.IntegerField(default=0, verbose_name='Индекс сортировки')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Проект',
                'ordering': ['-order_index'],
            },
        ),
    ]
