# Generated by Django 5.2.17 on 2026-08-16 07:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_description_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_problem',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание для блока Решение проблем'),
        ),
    ]
