# Generated by Django 5.2.17 on 2026-08-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_description_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='category',
            field=models.CharField(choices=[('text', 'С текстом'), ('big', 'Большое фото'), ('small', 'Фото на пол экрана')], default='big', max_length=20, verbose_name='Тип вывода'),
        ),
    ]
