# Generated by Django 4.2.19 on 2026-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='diploma/')),
                ('order_index', models.IntegerField(default=0, verbose_name='Индекс сортировки')),
            ],
            options={
                'verbose_name': 'Благодарственные письма',
                'verbose_name_plural': 'Благодарственные письма',
                'ordering': ['-order_index'],
            },
        ),
    ]
