# Generated by Django 4.2.15 on 2026-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diploma',
            options={'ordering': ['order_index'], 'verbose_name': 'Грамота / отзыв (Нам говорят спасибо)', 'verbose_name_plural': 'Грамоты / отзывы (Нам говорят спасибо)'},
        ),
        migrations.AddField(
            model_name='diploma',
            name='name',
            field=models.CharField(blank=True, help_text='Необязательно — для удобства в админке', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='avatar',
            field=models.ImageField(upload_to='diploma/', verbose_name='Изображение (грамота/отзыв)'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
