# Generated by Django 4.2.15 on 2026-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0002_alter_diploma_options_diploma_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Необязательно — для удобства в админке', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Изображение награды')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок отображения (меньше = первее)')),
            ],
            options={
                'verbose_name': 'Награда (блок «Награды»)',
                'verbose_name_plural': 'Награды (блок «Награды»)',
                'ordering': ['order_index'],
            },
        ),
        migrations.AlterModelOptions(
            name='diploma',
            options={'ordering': ['order_index'], 'verbose_name': 'Грамота / письмо (блок «Нам говорят спасибо»)', 'verbose_name_plural': 'Грамоты / письма (блок «Нам говорят спасибо»)'},
        ),
        migrations.AlterField(
            model_name='diploma',
            name='avatar',
            field=models.ImageField(upload_to='diploma/', verbose_name='Изображение (грамота или благодарственное письмо)'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='name',
            field=models.CharField(blank=True, help_text='Необязательно — только для удобства в админке, на сайте не показывается', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядок в слайдере (меньше = левее)'),
        ),
    ]
