# Generated by Django 4.2.15 on 2026-05-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название технологии')),
                ('icon', models.ImageField(blank=True, help_text='Логотип технологии (PNG/SVG, рекомендуется 32×32 px)', null=True, upload_to='tech/', verbose_name='Иконка')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок отображения (меньше = раньше)')),
            ],
            options={
                'verbose_name': 'Технология (блок «Fullstack-разработка»)',
                'verbose_name_plural': 'Технологии (блок «Fullstack-разработка»)',
                'ordering': ['order_index'],
            },
        ),
    ]
