# Generated by Django 4.2.15 on 2026-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['order_index'], 'verbose_name': 'Логотип клиента (блок «Нам доверяют»)', 'verbose_name_plural': 'Логотипы клиентов (блок «Нам доверяют»)'},
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(help_text='Рекомендуется PNG с прозрачным фоном', upload_to='client/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='client',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Порядок в карусели (меньше = левее)'),
        ),
    ]
