# Generated by Django 4.2.15 on 2026-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_section_image', models.ImageField(blank=True, help_text='Декоративное изображение справа внутри карточки', null=True, upload_to='site/', verbose_name='Картинка в блоке «Мы разрабатываем CRM/ERP»')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
