# Generated by Django 4.2.15 on 2026-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+7 924-375-05-73', help_text='Отображается в шапке и подвале сайта', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.CharField(default='https://t.me/', help_text='Полная ссылка, например: https://t.me/username', max_length=255, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='crm_section_image',
            field=models.ImageField(blank=True, help_text='Декоративное изображение справа в карточке', null=True, upload_to='site/', verbose_name='Картинка в блоке «Мы разрабатываем CRM/ERP»'),
        ),
    ]
